version: "3.7"

services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: redes
    restart: always

  web:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./source:/source
      - ./site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: always
    links:
      - php

  php:
    image: php:7.3-fpm
    container_name: php-container
    volumes:
      - ./source:/source
    links:
      - db

  memcached:
    image: memcached:alpine
    container_name: memcached-container
    ports:
      - 11211:11211
    command: -m 64
    restart: always
    links:
      - db